spring:
  datasource:
    url: jdbc:postgresql://localhost/craft_demo?serverTimezone=UTC&autoReconnect=true
    username: demo_user
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true